# Generated by Django 2.1.5 on 2019-06-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RemoveField(
            model_name='solution',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
    ]
