# Generated by Django 2.1.5 on 2019-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20190609_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
