# Generated by Django 2.1.5 on 2019-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
