# Generated by Django 2.1.5 on 2019-06-10 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20190609_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.09)]),
        ),
    ]
