# Generated by Django 2.1.5 on 2019-06-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20190610_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('title',)},
        ),
    ]
